---
# tasks file for roles/haproxy
- name: Install load balancer packages
  package:
    name: "{{ load_balancer_packages }}"
    state: present
  #tags: load_balancers

- name: Configure haproxy load balancing
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy
  #tags: load_balancers

- name: Enable Haproxy
  service:
    name: haproxy
    state: started
    enabled: true
  #tags: load_balancers
