---
- name: Play to setup mysql server
  hosts: database_servers
  roles:
    - role: pgsql

- name: Play to setup flask servers
  hosts: app_servers
  roles:
    - role: flask

- name: Play to setup HAproxy
  hosts: load_balancers
  roles:
    - role: haproxy
